image: node:20

variables:
  PNPM_VERSION: 8.9.0

cache:
  paths:
    - .pnpm-store
    - node_modules/
    - apps/*/node_modules/
    - packages/*/node_modules/

before_script:
  - npm install -g pnpm@$PNPM_VERSION
  - pnpm config set store-dir .pnpm-store
  - pnpm install

stages:
  - test
  - build
  - publish

test:
  stage: test
  script:
    - pnpm test

build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - packages/*/dist
      - apps/docs/storybook-static

publish-beta:
  stage: publish
  script:
    - |
      if [[ -n "${CI_MERGE_REQUEST_IID}" ]]; then
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        pnpm changeset version --snapshot beta
        pnpm publish -r --tag beta --no-git-checks
      fi
  only:
    - merge_requests

publish:
  stage: publish
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        pnpm changeset version
        pnpm publish -r
      fi
  only:
    - main